development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: minimarket_development
  pool: 5
  username: root
  password: ange92

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: minimarket_test
  pool: 5
  username: root
  password: ange92

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: minimarket_production
  pool: 5
  username: root
  password: ange92
